- .gitignore
- fluxctl/fluxctl.nuspec
- fluxctl/tools/chocolateyinstall.ps1
Upgrades fluxctl to version 1.21.0
> Feature/fluxctl upgrade version 1.21.0

- fluxctl/fluxctl.nuspec
- fluxctl/tools/chocolateyinstall.ps1
Updating fluxctl package to version 1.21.1
> Updating fluxctl package to version 1.21.1

- fluxctl/fluxctl.nuspec
- fluxctl/tools/chocolateyinstall.ps1
Updated fluxctl to version 1.23.2
> Updated fluxctl to version 1.23.2

- fluxctl/fluxctl.nuspec
- fluxctl/tools/chocolateyinstall.ps1
Updated fluxctl to version 1.24.0
> Updated fluxctl to version 1.24.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updated 'flux' to vresion 0.17.0. Added support for 64-bit executable.
> Updated 'flux' to vresion 0.17.0. Added support for 64-bit executable.

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updated flux to version 0.17.1
> Updated flux to version 0.17.1

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.18.3
> Updating flux2 package to version 0.18.3

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.20.1
> Updating flux2 package to version 0.20.1

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
- fluxctl/fluxctl.nuspec
- fluxctl/tools/chocolateyinstall.ps1
> Fluxctl 1.24.2

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.21.1
> Updating flux2 package to version 0.21.1

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.22.0
> Updating flux2 package to version 0.22.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.23.0
> Updating flux2 package to version 0.23.0

- fluxctl/fluxctl.nuspec
- fluxctl/tools/chocolateyinstall.ps1
Updating fluxctl package to version 1.24.3
> Updating fluxctl package to version 1.24.3

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.24.0
> Updating flux2 package to version 0.24.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.24.1
> Updating flux2 package to version 0.24.1

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.25.3
> Updating flux2 package to version 0.25.3

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.26.0
> Updating flux2 package to version 0.26.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.26.2
> Updating flux2 package to version 0.26.2

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.26.3
> Updating flux2 package to version 0.26.3

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.27.2
> Updating flux2 package to version 0.27.2

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.27.4
> Updating flux2 package to version 0.27.4

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.28.3
> Updating flux2 package to version 0.28.3

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.28.4
> Updating flux2 package to version 0.28.4

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.28.5
> Updating flux2 package to version 0.28.5

- fluxctl/fluxctl.nuspec
- fluxctl/tools/chocolateyinstall.ps1
Updating fluxctl package to version 1.25.0
> Updating fluxctl package to version 1.25.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.29.1
> Updating flux2 package to version 0.29.1

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.29.2
> Updating flux2 package to version 0.29.2

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.29.3
> Updating flux2 package to version 0.29.3

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.29.4
> Updating flux2 package to version 0.29.4

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.29.5
> Updating flux2 package to version 0.29.5

- fluxctl/fluxctl.nuspec
- fluxctl/tools/chocolateyinstall.ps1
Updating fluxctl package to version 1.25.1
> Updating fluxctl package to version 1.25.1

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.30.0
> Updating flux2 package to version 0.30.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.30.2
> Updating flux2 package to version 0.30.2

- fluxctl/fluxctl.nuspec
- fluxctl/tools/chocolateyinstall.ps1
Updating fluxctl package to version 1.25.2
> Updating fluxctl package to version 1.25.2

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.31.0
> Updating flux2 package to version 0.31.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.31.3
> Updating flux2 package to version 0.31.3

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.31.5
> Updating flux2 package to version 0.31.5

- fluxctl/fluxctl.nuspec
- fluxctl/tools/chocolateyinstall.ps1
Updating fluxctl package to version 1.25.3
> Updating fluxctl package to version 1.25.3

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.32.0
> Updating flux2 package to version 0.32.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.33.0
> Updating flux2 package to version 0.33.0

- fluxctl/fluxctl.nuspec
- fluxctl/tools/chocolateyinstall.ps1
Updating fluxctl package to version 1.25.4
> Updating fluxctl package to version 1.25.4

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.34.0
> Updating flux2 package to version 0.34.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.35.0
> Updating flux2 package to version 0.35.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.36.0
> Updating flux2 package to version 0.36.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.37.0
> Updating flux2 package to version 0.37.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.38.2
> Updating flux2 package to version 0.38.2

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.38.3
> Updating flux2 package to version 0.38.3

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.39.0
> Updating flux2 package to version 0.39.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.40.0
> Updating flux2 package to version 0.40.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.40.1
> Updating flux2 package to version 0.40.1

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.40.2
> Updating flux2 package to version 0.40.2

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.41.0
> Updating flux2 package to version 0.41.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.41.1
> Updating flux2 package to version 0.41.1

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 0.41.2
> Updating flux2 package to version 0.41.2

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.0.0-rc.4
> Flux 2.0.0 rc.4

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.0.0
> Updating flux2 package to version 2.0.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.0.1
> Updating flux2 package to version 2.0.1

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.1.0
> Updating flux2 package to version 2.1.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.1.1
> Updating flux2 package to version 2.1.1

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.1.2
> Updating flux2 package to version 2.1.2

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.2.0
> Updating flux2 package to version 2.2.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.2.1
> Updating flux2 package to version 2.2.1

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.2.2
> Updating flux2 package to version 2.2.2

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.2.3
> Updating flux2 package to version 2.2.3

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.3.0
> Updating flux2 package to version 2.3.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.4.0
> Updating flux2 package to version 2.4.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.5.0
> Updating flux2 package to version 2.5.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.5.1
> Updating flux2 package to version 2.5.1

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.6.0
> Updating flux2 package to version 2.6.0

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.6.2
> Updating flux2 package to version 2.6.2

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.6.3
> Updating flux2 package to version 2.6.3

- flux2/flux2.nuspec
- flux2/tools/chocolateyinstall.ps1
Updating flux2 package to version 2.7.1
> Updating flux2 package to version 2.7.1
